development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: books_store_development
  pool: 5
  username: kvarma
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: books_store_test
  pool: 5
  username: kvarma
  host: localhost
  port: 5432